language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "pociot-github" # the key of the org you chose at step #3
    token:
      secure: uwhaSuCM2uLYRtv5bd2gZHJfpkEx2rgzEvZWEiWho1elDqynR5Hrhg+xs2iIaxBRdhntuW9KXVhjXgkctlog1iNUOCafuembAF3WP5GsN1BykLVP+fUqsEhmIjATXG1LWmeaABcfaElQajwHyfdpbLcwH8fU4OOc9uA7ChTE0iK8weBmTSaJSOUdKhDn1+rilkPLkBegEsFa/sAl8gOb0/7sXBlbWB5gZzXeo+I33y0wuNYPlLId/HeUVh2b40p0dcDkqDFxaQ1pUsxo6EHvJ6sIghAw4si/tJZ5fRH7chlF+R4R08SGs2Xt0XYSbWjr/wH+6qiethtvpPDO/j0qaQgi9OyIiUtc89Zlf1/1H/C7vrG56lDH7etsEybkLhHrgYGw6oPv8p+VJz0N/uwT9jsqpf53LwqaF3ytTocTFcnbqD/vlPuOrazaibALfSRLHvCfcxoYSmZfPF60XdbX9lWPU3D7gD8VV4GJ0t1Y8PDWgujmd9YDxpUPdzZucAkiLZ97Tdi/EpG02oT7e5PiW+qdHNx5Lx9PLO2XK25wF2fDV7L+mipP2HbPWeBQQPuiV1sJZq0w5ee9L6pIhiFi6FZ6Cm0Vttr9bR9h9OTC9xhaBvW2G3v+XakEUIOGZuaXxZr5fprs0deAZsAxHOuBMtduMb7wCKbUT+RPL0lF9QQ=
script:
- yarn run build
- sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: iptfv+6VAmvHsyBbSjnooreJ7hQEJ6Dc2auj1l4DlEF+9+m6Rq3Z8GZrWuguKuV/6SWSCi19oNH3zhoHWmb+PYyA/HvKsS9ZhO2qjXuSX0J7rwDNyrejF84d8GMrC6SFpRouTgKcn+vVtFGTx8aaFync4yFjXHk+5OiJfMz9zlwCQZl5Jc2Qc7AR6JHNdSZL6j8P5QZMlg0JKZlH1cDQj3dhOoXwXeFCtpaJiInzn6liwJqa1h3ODMUCuP1+NPG4GOu5zNILN2tztw0TggItSVxdVGGV1n4IdEr8R4EbeIkNyDfUpPAWXAvYpWJbLsJ2+hPKtY9N2HBm22vu0tgYciBTvXUrxoXh4KueVD5RxbJYPW9Gf8bPpVkaVu6HYKB1ViIg78qp6eWGYm/KXuZZfLcr/18p36bj3uiImuq0jR1JWixtbqxOyRwCsUuw7pgKrb3jefpqHLveJByHVZKghmrzlLqXwRl9wyMdyazSN+VIxiGYTpTsTWVRIOZr2nEDJU2XIWzdkzwuLiQ2j71LAT8EBeBvxnzNkVAaTaFoNvP0f8LbIiShfqpfYvLUS4ME68hnTz/72qKJyq+OvHlS1EJoPzlCjCH+a5+cSPk9j00sPihWcB4mjUtd1MvhqZle2giUiPGtDd8gA1Jd8I5L5iRghJfxct4Pr9xW/GUpj+g=
  app: accounting-kpociot
  on:
    repo: pociot/accounting-frontend
