language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
  - yarn run build
deploy:
  provider: heroku
  api_key:
    secure: iptfv+6VAmvHsyBbSjnooreJ7hQEJ6Dc2auj1l4DlEF+9+m6Rq3Z8GZrWuguKuV/6SWSCi19oNH3zhoHWmb+PYyA/HvKsS9ZhO2qjXuSX0J7rwDNyrejF84d8GMrC6SFpRouTgKcn+vVtFGTx8aaFync4yFjXHk+5OiJfMz9zlwCQZl5Jc2Qc7AR6JHNdSZL6j8P5QZMlg0JKZlH1cDQj3dhOoXwXeFCtpaJiInzn6liwJqa1h3ODMUCuP1+NPG4GOu5zNILN2tztw0TggItSVxdVGGV1n4IdEr8R4EbeIkNyDfUpPAWXAvYpWJbLsJ2+hPKtY9N2HBm22vu0tgYciBTvXUrxoXh4KueVD5RxbJYPW9Gf8bPpVkaVu6HYKB1ViIg78qp6eWGYm/KXuZZfLcr/18p36bj3uiImuq0jR1JWixtbqxOyRwCsUuw7pgKrb3jefpqHLveJByHVZKghmrzlLqXwRl9wyMdyazSN+VIxiGYTpTsTWVRIOZr2nEDJU2XIWzdkzwuLiQ2j71LAT8EBeBvxnzNkVAaTaFoNvP0f8LbIiShfqpfYvLUS4ME68hnTz/72qKJyq+OvHlS1EJoPzlCjCH+a5+cSPk9j00sPihWcB4mjUtd1MvhqZle2giUiPGtDd8gA1Jd8I5L5iRghJfxct4Pr9xW/GUpj+g=
  app: accounting-kpociot
  on:
    repo: pociot/accounting-frontend
